### ISSUE TITLE
Create and update documentation for Axel-GME

### ISSUE THREAD

**Issue by shinsean** [seanshin2647/Axel-GME#13]
I have been told I need better documentation for this repo. I have stopped development on this because I am occupied with other projects.

Create a CONTRIBUTING.md edited for this program from https://github.com/seanshin2647/BUBC-Universal-Bookmark-Converter.

**Comment by icewilktea** [comment]
I can do it.

**Comment by shinsean** [comment]
Got it, then please do so.

**Comment by shinsean** [comment]
Closed with PR #14.
